### ISSUE TITLE
OS: Mac - Screenshot gets written only on 1st level directory

### ISSUE THREAD

**Issue by NerdishShah** [extent-framework/extentreports-cucumber4-adapter#6]
On Mac, the screenshots get written on 1st level directory i.e. given test-output/html/screenshots in extent.properties gets written only on test-output folder.

**Comment by anshooarora** [comment]
@NerdishShah I am unable to reproduce this on Ubuntu or Windows. I don't have a Mac do unable to test. 

Please note, if you have the below runner options, screenshots will be created in `test-output` along with the folder specified in `extent.properties` because the Cucumber hooks will create snapshots in `test-output/`.

```
@CucumberOptions(plugin = {
    "com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:",
    "json:target/cucumber-report.json"
})
```

Can you remove the Cucumber hook, try again and report your results?

```
@CucumberOptions(plugin = {
    "com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"
})
```

**Comment by anshooarora** [comment]
I am closing this as there is no response.  Feel free to reopen or create a new issue if it persists.
