### ISSUE TITLE
extentreports-cucumber6-adapter : attaching screenshot to extent report doesnt work

### ISSUE THREAD

**Issue by gbalaji94** [extent-framework/extentreports-cucumber4-adapter#62]
Hi @anshooarora 

I am using extentreports-cucumber6-adapter, 

```
        <dependency>
            <groupId>tech.grasshopper</groupId>
            <artifactId>extentreports-cucumber6-adapter</artifactId>
            <version>1.0.0</version>
            <scope>test</scope>
        </dependency>
```
Issues : 

1. Scenario.embed doesn't work.
2. Alternatively, I could use 
           ` scenario.attach(screenshot, "image/png", scenario.getName());`

This adds the attachment icon to the report, but the image is empty. Can you please help?

**Comment by anshooarora** [comment]
@gbalaji94 This would be the correct repository for this issue:  https://github.com/grasshopper7/extentreports-cucumber6-adapter.   Copying @grasshopper7

This can be fixed by using a relative path from https://github.com/extent-framework/extentreports-cucumber4-adapter/blob/master/config/extent.properties#L31

```
extent.reporter.spark.out=test-output/SparkReport/

screenshot.dir=test-output/
screenshot.rel.path=../
```

So considering the above, if you are saving your report in `test-output/SparkReport/Spark.html`, and your images to `test-output/`, your relative path would be to tell the report to look 1 level up, from `SparkReport/.html -> test-output`.  Thus the `../../` as the relative path.

**Comment by grasshopper7** [comment]
@gbalaji94 If u are still having the issue even after trying the settings above, feel free to open an issue at - https://github.com/grasshopper7/extentreports-cucumber6-adapter/issues. Thanks

**Comment by lgjsherond** [comment]
Screenshot not generating once it failed. Please find the attached files. Or shall I need to generate the screenshot with the help of a webdriver. 

![image](https://user-images.githubusercontent.com/50234665/98557816-ae6c3f80-22ca-11eb-9323-6353278c692a.png)

![image](https://user-images.githubusercontent.com/50234665/98557886-c47a0000-22ca-11eb-9633-843eba3177e7.png)
